Resolves #66
UFRN-URNAI/urnai-tools pull request #77
Opened 2023-11-27 17:45 UTC by RickFqt

- Resolves #66.

2023-11-28 13:36 UTC, alvarofpp requested changes
I noticed that the commits are not in the right pattern. There is no capital letter after the `:`.

2023-11-28 13:36 UTC, alvarofpp commented on urnai/environments/abenv.py
> +sys.path.insert(0, parentdir)
That looks like a workaround. It's interesting that we don't put this in the new version of the package.

2023-11-28 13:36 UTC, alvarofpp commented on urnai/environments/abenv.py
> +        self.id = _id
Usually, the use of `_` at the beginning of variables is used to represent something that the developer should not manipulate, such as private variables used for the behavior of a particular script. Why is this in the first parameter of the function?

2023-11-28 13:36 UTC, alvarofpp commented on urnai/utils/returns.py
> +Reward = int
In the future we'll have a class for this, so it shouldn't exist here.

2023-11-28 13:36 UTC, alvarofpp commented on urnai/utils/returns.py
> +Observation = List[Any]
In the future we'll have a class for this, so it shouldn't exist here.

2023-11-28 13:36 UTC, alvarofpp commented on urnai/utils/__init__.py
Modules like `utils` or `helpers` are discouraged, as this implies that you have failed to define a proper scope for the function/class.

2023-11-28 13:36 UTC, alvarofpp commented on urnai/environments/abenv.py
> +    """
For Python's `help` function to work properly, this comment must be inside the function it belongs to. In this case, this comment should be just below the signature of the `start` function. This review applies to all subsequent comments in the file.

2023-11-28 13:37 UTC, alvarofpp commented
One last thing I forgot to mention: all the code must be covered by unit tests.

2023-11-28 14:16 UTC, RickFqt commented
> I noticed that the commits are not in the right pattern. There is no capital letter after the `:`.

To fix this, should I undo the commits, or rename them with git rebase?

2023-11-28 14:28 UTC, alvarofpp commented
> To fix this, should I undo the commits, or rename them with git rebase?

I recommend using `git rebase` to rewrite the commits, then `git push -f` on your branch.

2023-11-29 10:33 UTC, RickFqt commented on urnai/utils/returns.py
> +Observation = List[Any]
So, in the base environment class, should Done, Reward, and Observation be replaced by their raw types? (bool, int, int and List[Any])
Like this, for example:
![image](https://github.com/UFRN-URNAI/urnai-tools/assets/102550763/b38fe7b6-d28d-43a2-a8ec-fb1ab424e579)

2023-11-29 13:33 UTC, alvarofpp commented on urnai/utils/returns.py
> +Observation = List[Any]
Yep 👍🏻

2023-11-29 13:34 UTC, alvarofpp commented
Just a reminder of something you should do at the end of all this: use `git rebase` to put everything into a single commit.

2023-11-29 18:13 UTC, RickFqt commented on urnai/environments/abenv.py
> +        self.id = _id
The first parameter of the function should receive an identifier of the current environment (like a map's name in the case of a StarCraft II environment), but I don't really see the use of `_` here. Should I remove it?

2023-11-30 14:13 UTC, RickFqt commented
> One last thing I forgot to mention: all the code must be covered by unit tests.

About these unit tests, is there any reference that can be used as a model to do them? Also, will they work like this lint job that runs to check if the code is okay to merge?

Another question: how should we make tests for abstract methods in these base classes we are going to create? I understand how they should work on implementations of these classes (like a Starcraft II environment class, for example), but I don't see how to do them in the base classes.

2023-12-06 15:35 UTC, alvarofpp commented on urnai/environments/abenv.py
> +        self.id = _id
> Should I remove it?

Yes.

2023-12-06 15:44 UTC, alvarofpp commented
@RickFqt 

> About these unit tests, is there any reference that can be used as a model to do them?

> Another question: how should we make tests for abstract methods in these base classes we are going to create? I understand how they should work on implementations of these classes (like a Starcraft II environment class, for example), but I don't see how to do them in the base classes.

This is our first abstract class, so we don't have any tests to use as a base. I found some links on the internet that might be useful for you:

- https://clamytoe.github.io/articles/2020/Mar/12/testing-abcs-with-abstract-methods-with-pytest/
- https://copyprogramming.com/howto/python-testing-an-abstract-base-class

> Also, will they work like this lint job that runs to check if the code is okay to merge?

Yes, we'll have a job to check test coverage. You can run all of this (linter and tests) locally using the `task lint`, `task unit-test`, and `task test-coverage` commands.

2023-12-19 13:07 UTC, RickFqt commented
> Yes, we'll have a job to check test coverage.



> You can run all of this (linter and tests) locally using the `task lint`, `task unit-test`, and `task test-coverage` commands.

Tried to run linter locally here, but keep getting this error message:
![image](https://github.com/UFRN-URNAI/urnai-tools/assets/102550763/dcb4ac9b-4470-4df7-a718-6a9e8a81b9eb)
I searched a little bit about this error message, but couldn't find anything to solve it. Do you know what might be causing it?

Also got error messages for running the test commands, but I think that is because we don't have any tests implemented yet. Is that right?
![image](https://github.com/UFRN-URNAI/urnai-tools/assets/102550763/31e07ae0-2e51-42d0-a858-60b3156b01a7)
![image](https://github.com/UFRN-URNAI/urnai-tools/assets/102550763/c13fc48d-4159-4a57-8341-05be4309d2ce)

2023-12-19 13:20 UTC, alvarofpp commented
> I searched a little bit about this error message, but couldn't find anything to solve it. Do you know what might be causing it?

We can ignore this error for now. To do this, add the line below to the beginning of the failed files:

```yaml
# yamllint disable rule:new-lines
```

And add the line below at the end of the failed files:

```yaml
# yamllint enable
```

> Also got error messages for running the test commands, but I think that is because we don't have any tests implemented yet. Is that right?

That's exactly why.

2024-02-06 13:26 UTC, RickFqt commented
> That's exactly why.

So, about the unit tests, where should they be implemented? I'm trying to do that inside [tests/units](https://github.com/UFRN-URNAI/urnai-tools/tree/v2/tests/units), but keep getting the same error as before.

2024-02-06 13:34 UTC, alvarofpp commented
> So, about the unit tests, where should they be implemented? I'm trying to do that inside [tests/units](https://github.com/UFRN-URNAI/urnai-tools/tree/v2/tests/units), but keep getting the same error as before.

You should create a Fake class to inherit from `EnvironmentBase` and apply the tests to it. It's OK to create this class inside the test file, as it will only be used for this purpose.

2024-02-06 13:35 UTC, alvarofpp commented
Another thing: the name `abenv.py` is not explicit. I recommend renaming the file `environment_base.py.`

2024-02-06 16:28 UTC, RickFqt commented
> You should create a Fake class to inherit from `EnvironmentBase` and apply the tests to it. It's OK to create this class inside the test file, as it will only be used for this purpose.

Based on the links recommended, I wrote the following test:

```python
from abc import ABCMeta
from urnai.environments.environment_base import EnvironmentBase
import unittest

class TestEnvironmentBase(unittest.TestCase):

    def test_environment_base(self):
        EnvironmentBase.__abstractmethods__ = set()

        class EnvironmentDummy(EnvironmentBase):
            def __init__(self, id: str, render=False, reset_done=True):
                super().__init__(id, render, reset_done)

        d = EnvironmentDummy("id")
        start_return = d.start()
        step_return = d.step("action")
        reset_return = d.reset()
        close_return = d.close()
        assert isinstance(EnvironmentBase, ABCMeta)
        assert start_return is None
        assert step_return is None
        assert reset_return is None
        assert close_return is None
```
I wasn't sure what to put into the "id" and "action" paramaters from the initializer and step, so I just put these strings. ID is supposed to be a string, but I'm not sure about the action parameter.

Also, I wasn't able to use `task unit-test` to run this test, although I could run it normally with pytest locally here. Is there a reason for that?

2024-02-06 20:49 UTC, alvarofpp commented
You're going in the right direction, a few suggestions:

- I think the function name could be more explicit than just repeating the class name.
- It would avoid the use of Dummy, the reason for which you can see [here][dummy].

> Also, I wasn't able to use `task unit-test` to run this test, although I could run it normally with pytest locally here. Is there a reason for that?

Can you post a printout of what happens when you run `task unit-test`?

💡 Tip: you can upload the unit test code so we can see it better. Before the merge, you can merge commits, change their texts, etc.

[dummy]: https://itconnect.uw.edu/guides-by-topic/identity-diversity-inclusion/inclusive-language-guide/#:~:text=no%20meaningful%20value.-,Why%20it's%20problematic%3A,alternative%20word%20should%20be%20used.

2024-02-07 12:20 UTC, RickFqt commented
> Can you post a printout of what happens when you run `task unit-test`?

The error is just like in here:

> Also got error messages for running the test commands, but I think that is because we don't have any tests implemented yet. Is that right? ![image](https://private-user-images.githubusercontent.com/102550763/291592876-31e07ae0-2e51-42d0-a858-60b3156b01a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMDc5NTQsIm5iZiI6MTcwNzMwNzY1NCwicGF0aCI6Ii8xMDI1NTA3NjMvMjkxNTkyODc2LTMxZTA3YWUwLTJlNTEtNDJkMC1hODU4LTYwYjMxNTZiMDFhNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QxMjA3MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NjQ4MmQ4M2IxMjQyNTFmNTU1NzUyM2Y2N2QzMTQwN2EzMjgxZmRjYTZkYTFmZjllNGM3YzhkYjE3ZTVjNGVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ddOGNVUx4KOrJ8Ga4uoa17Tc8vrZQky4CEeyWs4wiCQ) 

> 💡 Tip: you can upload the unit test code so we can see it better. Before the merge, you can merge commits, change their texts, etc.

I've just tried to upload the test code, but keep getting this error:

![image](https://github.com/UFRN-URNAI/urnai-tools/assets/102550763/e6d9ff71-b218-4436-ab44-88ac0729138b)

2024-02-07 13:14 UTC, alvarofpp commented
This error occurs because of githook. Try running the push command, but add the `--no-verify` flag.

2024-02-16 00:11 UTC, alvarofpp commented
@RickFqt I've taken the liberty of making the changes directly in the code (I've taken the opportunity to update our linter image, https://github.com/UFRN-URNAI/docker-images/pull/6 ).

2024-02-16 16:04 UTC, RickFqt commented
> @RickFqt I've taken the liberty of making the changes directly in the code (I've taken the opportunity to update our linter image, [UFRN-URNAI/docker-images#6](https://github.com/UFRN-URNAI/docker-images/pull/6) ).

Now, `task test-coverage` works, but it shows that 0% of the code is covered:
![image](https://github.com/UFRN-URNAI/urnai-tools/assets/102550763/cffd0fa9-5e1c-4a3e-b5ed-68d813dfd868)

Also, when I try `task unit-test`, I now receive another error:
[TaskUnitTestError.txt](https://github.com/UFRN-URNAI/urnai-tools/files/14312489/TaskUnitTestError.txt)

One more thing: I tried to use `task-lint` just to check if it was working, and I'm not sure if it is detecting problems in the code correctly. Before, it gave me a check mark that everything was correct, but now it doesn't seem to show anything. For example, I tried to delete some comments, add some random newlines in [environment_base.py](https://github.com/UFRN-URNAI/urnai-tools/blob/issue-66/urnai/environments/environment_base.py) and ran `task-lint`, but it didn't warn anything. It was just like this:
![image](https://github.com/UFRN-URNAI/urnai-tools/assets/102550763/fadc1010-ef2d-42ed-b676-379d3e69ff23)

2024-02-16 17:58 UTC, alvarofpp commented
I tried to reproduce that test error locally and was unsuccessful. Try deleting the `.coverage` file and running `task unit-test test-coverage` again. Also try building the image again.

The linter is indeed strange, I'll check it at some point.

2024-02-16 21:44 UTC, alvarofpp commented
@RickFqt I fixed the problem with the Python linter, I had forgotten to enter which rules it should consider when evaluating the code. The Docker image has already been updated and I've fixed the files here in your branch.

2024-02-16 21:45 UTC, alvarofpp approved these changes
@RickFqt Try running the tests for your code locally. If all goes well, you can merge it.

2024-02-17 12:53 UTC, RickFqt commented
> @RickFqt Try running the tests for your code locally. If all goes well, you can merge it.

Locally, it went well. Thanks!

2024-02-17 12:58 UTC, merged