Resolves #76
UFRN-URNAI/urnai-tools pull request #92
Opened 2024-06-21 13:32 UTC by CinquilCinquil

#76

2024-07-01 18:41 UTC, CinquilCinquil commented
I think the ActionSpace an agent receives could be replaced by an Strategy class (the class responsible for choosing the agent's next action), what do you think? @alvarofpp

2024-07-01 18:43 UTC, CinquilCinquil commented
It should at least receive a Strategy class if im understanding their relationship correctly.

2024-07-01 19:33 UTC, CinquilCinquil commented
Hey, i tried rebasing to a newer version of v2 to make some adjustments in the code, but it appears that the old commits were duplicated when i commited the new changes. Any suggestions on how to fix this? or should i just ignore them?

2024-07-05 13:55 UTC, alvarofpp commented
> Any suggestions on how to fix this? or should i just ignore them?

I recommend creating a new branch from `v2` and cherry-picking your commits about issue 76.

2024-07-05 14:01 UTC, alvarofpp requested changes

2024-07-05 14:01 UTC, alvarofpp commented on tests/units/agents/test_agent_base.py
> +    ...
I don't think this `...` is necessary.

2024-07-05 14:01 UTC, alvarofpp commented on tests/units/agents/test_agent_base.py
> +    ...
I don't think this `...` is necessary.

2024-07-05 14:01 UTC, alvarofpp commented on tests/units/agents/test_agent_base.py
> +    ...
I don't think this `...` is necessary.

2024-07-05 14:01 UTC, alvarofpp commented on tests/units/agents/test_agent_base.py
> +    ...
I don't think this `...` is necessary.

2024-07-05 14:01 UTC, alvarofpp commented on tests/units/agents/test_agent_base.py
> +    ...
I don't think this `...` is necessary.

2024-07-05 14:01 UTC, alvarofpp commented on tests/units/agents/test_agent_base.py
> +                               fake_model, fake_reward_builder)
```suggestion
        fake_agent = FakeAgent(
            fake_action_space,
            fake_state_space,
            fake_model,
            fake_reward_builder
        )
```

2024-07-05 14:01 UTC, alvarofpp commented on tests/units/agents/test_agent_base.py
> +
It is not necessary to leave a blank line after the function signature.

2024-07-05 14:01 UTC, alvarofpp commented on tests/units/agents/test_agent_base.py
> +        self.assertEqual(state_dim_return, fake_state_space.dimension)
```suggestion
    def test_state_dim(self):
        # GIVEN
        fake_state_space = FakeState()

        # WHEN
        fake_agent = FakeAgent(None, fake_state_space, None, None)

        # THEN
        self.assertEqual(fake_agent.state_dim, fake_state_space.dimension)
```

2024-07-12 15:58 UTC, CinquilCinquil commented
To fix the duplicated commits i continued this issue on another branch (issue-76-2) on [this ](https://github.com/UFRN-URNAI/urnai-tools/pull/94)pull request

2024-07-12 20:02 UTC, closed without merging