Resolves #74
UFRN-URNAI/urnai-tools pull request #93
Opened 2024-07-01 18:27 UTC by CinquilCinquil

#74

2024-07-05 14:04 UTC, alvarofpp requested changes

2024-07-05 14:04 UTC, alvarofpp commented on urnai/strategies/strategy_base.py
> +    def choose_action(self, action_space : ActionSpaceBase) -> ActionBase:
```suggestion
    def choose(self, action_space : ActionSpaceBase) -> ActionBase:
```

2024-07-05 20:57 UTC, CinquilCinquil commented
Due to a discussion in a meeting, there is not going to be a Strategy class anymore and this issue will now be about the implementation of a ```choose_action``` method in the Agent class.

2024-07-14 22:19 UTC, alvarofpp approved these changes

2024-07-14 22:21 UTC, merged

2024-07-14 22:23 UTC, alvarofpp commented
Only close this issue after #94 is merged.